path_classifiers:
  test:
      - exclude: "**/test_*"

extraction:
  python:
    python_setup:
        requirements:
          - cython>=0.29
  cpp:
    index:
      build_command:
        - python3 setup.py build
    after_prepare:
      - pip3 install --upgrade --user cython
      - export PATH="$HOME/.local/bin:$PATH"

queries:
  - include: py/file-not-closed