sudo: false

language: python
python:
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    
      language: shell       
    - name: "Python 3.7.4 on Windows"
      os: windows           
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: 
  - pip3 install -U pip 
  - pip3 install -U psutil cython numpy
  - python setup.py install

script: pytest