sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache

language: python
python:
  - "3.6"
  - "3.7"

branches:
  only:
    - develop

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           
    # - name: "Python 3.7.4 on macOS"
    #   os: osx
    #   osx_image: xcode11    
    #   language: shell       
    # - name: "Python 3.7.4 on Windows"
    #   os: windows           
    #   language: shell
    #   before_install:
    #     - choco install python
    #     - python -m pip install --upgrade pip
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  # allow_failures:
  #   - windows

install: 
  - pip install -U pip coveralls
  - pip install -U psutil cython numpy
  - pip install .

script:
  coverage run --source fse setup.py test

after_success:
  coveralls
